### ISSUE TITLE
refs #4 Topの作成

### ISSUE THREAD

**Issue by gembaf** [SLP-KBIT/Attereco-Front#13]
- [x] 「カードをかざしてください」の文字を表示
- [x] 学籍番号と送信ボタンを配置
  - [x] ボタンをWindowsMetroっぽく

**Comment by gembaf** [comment]
ごめんMetroっぽくが分からなかったんで後は任せます。

**Comment by MaxMEllon** [comment]
別アプリで使ったリソースディクショナリがあるのでそれ使ってやっておきます
